### ISSUE TITLE
tags show as "tag object" in submit thread

### ISSUE THREAD

**Issue by BanzaiTokyo** [BanzaiTokyo/askapp#12]
When you submit thread the tags show in the form as "tag object" instead of actually showing the text of the tag. See the screenshot.

![screenshot from 2017-01-04 15-12-09](https://cloud.githubusercontent.com/assets/2467506/21644963/67eba96c-d290-11e6-8213-1fe7d56ac976.png)

**Comment by toxa23** [comment]
Unconfirmed. Is your askapp_tag table populated with tag names and slugs?
