### ISSUE TITLE
on thread page the image may overlap the right column

### ISSUE THREAD

**Issue by BanzaiTokyo** [BanzaiTokyo/askapp#16]
And while we are at it, a <br> or something may be added before the image to unstick it from the thread info. 
![threadpage](https://cloud.githubusercontent.com/assets/2467506/21651471/0a7da32a-d2a9-11e6-87b9-1ec2b3e04291.png)

**Comment by toxa23** [comment]
Just play with HTML markup in templates/thread.html lines 45-49
