### ISSUE TITLE
Hide "down" button on thread page for regular users

### ISSUE THREAD

**Issue by BanzaiTokyo** [BanzaiTokyo/askapp#30]
users who are not admins should not see the "down" button.
![downbutton](https://cloud.githubusercontent.com/assets/2467506/22106998/d115d856-de4b-11e6-9fb9-c8c72eda1c8a.png)

**Comment by BanzaiTokyo** [comment]
it might actually be manifestation d'un autre bug: posting as a regular user sublits Thread as admin.

**Comment by toxa23** [comment]
not a bug, duplicate of #28
