### ISSUE TITLE
Submitting a comment as a guest

### ISSUE THREAD

**Issue by BanzaiTokyo** [BanzaiTokyo/askapp#33]
When you submit a comment while not logged in, it should take you to the login form and if the login successful post the comment after that. Right now there is an error 
![img_7463](https://cloud.githubusercontent.com/assets/2467506/22187324/a55d799c-e104-11e6-884c-5bca837fa662.PNG)

**Comment by toxa23** [comment]
The form shouldn't be visible to guests. Fixed.
