### ISSUE TITLE
look into error displaying http://akihabara.tokyo/tags/?sort=used&page=None

### ISSUE THREAD

**Issue by BanzaiTokyo** [BanzaiTokyo/askapp#47]
it should redirect to 404 error page

**Comment by toxa23** [comment]
>You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.

Will it solve the problem?

**Comment by BanzaiTokyo** [comment]
indeed! it looks like a fix :)
I just wanted to make sure that with Debug = False it will display regular
404
