### ISSUE TITLE
link to comments on question page

### ISSUE THREAD

**Issue by BanzaiTokyo** [BanzaiTokyo/askapp#52]
I wonder if it was intentional or not, but the comments' ids on the question and on the answer don't link anywhere (even though they are highlighted as links). I would rather the link was functional but the comment functionality on that page was disabled. See the images for comments 12747, 12749 and 12750
 
![linktocomments](https://cloud.githubusercontent.com/assets/2467506/22710986/bdf47f00-ed7f-11e6-9c80-a3cfd839f77d.jpg)

**Comment by toxa23** [comment]
Yes, this was intentional, because question comments cannot be replied.

**Comment by BanzaiTokyo** [comment]
one of the two thinkgs need to be done:
1. if it is not a link it should not be styled as a link
2. if it links to a comment page and this comment doesn't accept replies, the textfield and submit button should not be displayed on the comments page.

I would prefer the second option.
