### ISSUE TITLE
changing question to discussion removes answers

### ISSUE THREAD

**Issue by BanzaiTokyo** [BanzaiTokyo/askapp#60]
I have changed the type of the thread http://akihabara.tokyo/thread/9312/ryokans-vs-airbnb/ from question to discussion. It was a test rather than necessity. I have noticed that the answers that were posted to the thread disappeared. Can we convert them to comments instead of hiding them?

**Comment by toxa23** [comment]
Do you want to mix the answers up with the question comments?

**Comment by BanzaiTokyo** [comment]
@toxa23 yeah, I think this is the only possibility.
