### ISSUE TITLE
Limit the number of upvotes per day

### ISSUE THREAD

**Issue by BanzaiTokyo** [BanzaiTokyo/askapp#64]
Any user except administrators should have a limited number of upvotes (*) per day.

 * initial number of upvotes = 3, this value should be changeable in the site settings

**Comment by toxa23** [comment]
Only upvotes should be limited, or downvotes as well?

**Comment by BanzaiTokyo** [comment]
@toxa23 sorry I didin't express it well - the number of any votes (up or down) should be limited.

**Comment by BanzaiTokyo** [comment]
@toxa23 update: I didn't give it much thought. But it is only admins who can down vote threads, regular users can only upvote them.
