### ISSUE TITLE
user's private page that shows threads she liked

### ISSUE THREAD

**Issue by BanzaiTokyo** [BanzaiTokyo/askapp#65]
Just a list of threads. The goal is to allow the user to have a collection of threads that she found interesting. Something like "to read later".

This page should not be visible to other users, only to administrators.

**Comment by toxa23** [comment]
I've called it "Favorite threads". In a threads list there is a "star" icon below the thread type icon that allows to add/remove the thread to the "favorites" list. This list can be reached by the main menu button "Favorite threads". This list is also visible at "/profile/:id" page for admins.

**Comment by BanzaiTokyo** [comment]
Tested, works like a charm!
