### ISSUE TITLE
domain list page

### ISSUE THREAD

**Issue by BanzaiTokyo** [BanzaiTokyo/askapp#66]
Page that lists domains for the links (threads of type "link") in order of popularity. 
Such a page would allow to analyse which sites have been most linked to.
The table should have the following columns: 
- domain
- number of articles that link to this domain
- average point that an article from this domain received

The table should allow ordering by domain name, number of threads, average number of points
The table should allow to take into account threads only from all the time, the past moth, week, day

**Comment by toxa23** [comment]
@BanzaiTokyo review it, please.

**Comment by toxa23** [comment]
Currently the list is limited to 10 entries. Should it display all domains?

**Comment by BanzaiTokyo** [comment]
from what I can see the number of entries can be modified in the site settings. Everything works great, I would just make default ordering by the (descending) number of articles.
