### ISSUE TITLE
remove user and all her content

### ISSUE THREAD

**Issue by BanzaiTokyo** [BanzaiTokyo/askapp#67]
When an administrator edits a user he should be able to click a button that marks the user and all her content as deleted.

**Comment by toxa23** [comment]
What's the difference to "make the user inactive"? Same, but also delete the user?

**Comment by BanzaiTokyo** [comment]
@toxa23 if I am not mistaken, inactive and deleted is the same thing. What is needed is a button on the user edit page available to admin that not only marks the user inactive but also removes all his content  (mark it as deleted).
Imagine a situation where a spammer creates an account and posts his links all over a place - we need an easy way to remove it all. The user can be removed from the admin panel, but it would be nice to be able to remove it from the front end as well.

**Comment by BanzaiTokyo** [comment]
@toxa23 if I am not mistaken, inactive and deleted is the same thing. What is needed is a button on the user edit page available to admin that not only marks the user inactive but also removes all his content  (mark it as deleted).
Imagine a situation where a spammer creates an account and posts his links all over a place - we need an easy way to remove it all. The user can be removed from the admin panel, but it would be nice to be able to remove it from the front end as well.

**Comment by toxa23** [comment]
There is such "button". Actually it is not a button, but the "Active" checkbox. Unchecking it deletes all user's content and make the user inactive.

**Comment by BanzaiTokyo** [comment]
@toxa23 awesome, this is exactly the functionality I was looking for! Sorry I overlooked the "active" checkbox.
