### ISSUE TITLE
switching betweet languages fails

### ISSUE THREAD

**Issue by BanzaiTokyo** [BanzaiTokyo/askapp#68]
after changing the language on the page, the settings parameter: LANGUAGE_CODE = 'en' is no longer taken into effect.

**Comment by toxa23** [comment]
This is not a bug, but a Django feature. First it searches for a language code in the session, then in the cookies and finally in HTTP header "HTTP_ACCEPT_LANGUAGE" (which is set for most visitors). And only if none of the 3 above options is found, it uses language code from the settings.
Fixed it by a code snippet https://gist.github.com/vstoykov/1366794
