### ISSUE TITLE
Change MySQL to PostgreSQL

### ISSUE THREAD

**Issue by BanzaiTokyo** [BanzaiTokyo/askapp#80]
Postgres is a more popular database than MySQL right now. SO wouldn't it make sense to migrate AskApp to Postgres?

**Comment by toxa23** [comment]
Uber, Airbnb, Pinterest, Netflix, Udemy, Amazon, Twitter, Shopify and many others don't think Postgres is better :)

**Comment by BanzaiTokyo** [comment]
you are right https://stackshare.io/mysql :)
I thought that MySQL was already considered legacy. No problem, let's keep
it for now.
